name: CI

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  code-quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
          token: ${{ secrets.LOAN_API_PAT_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Perform prerelease checks
        run: pnpm run prerelease

  semver:
    name: Bump Version
    runs-on: ubuntu-latest
    timeout-minutes: 2
    needs: code-quality
    if: github.ref == 'refs/heads/master'

    permissions:
      contents: write

    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}

    steps:
      - uses: actions/checkout@v4

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch

  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: semver
    if: github.ref == 'refs/heads/master'

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
          token: ${{ secrets.LOAN_API_PAT_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --filter infra...

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_PROD }}:role/github-actions-cdk-deploy
          aws-region: eu-north-1

      - name: CDK deploy
        run: pnpm run cdk:deploy --all --no-color --require-approval never