name: CI

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  code-quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - uses: actions/checkout@v6.0.2
        with:
          submodules: 'true'

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v6.3.0
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Perform prerelease checks
        run: pnpm run prerelease

  deploy:
    name: Deploy
    environment: production
    runs-on: ubuntu-latest
    timeout-minutes: 2
    needs: code-quality

    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v6.0.2
        with:
          submodules: 'true'

      - name: Bump version and push tag
        id: tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ""
          default_bump: patch

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v6.3.0
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --filter infra...

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_PROD }}:role/github-actions-cdk-deploy-north-1
          aws-region: eu-north-1

      - name: Perform release
        run: pnpm run cdk:deploy --require-approval broadening
