name: Master Checks (and Deploy)

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

permissions:
  contents: read
  pull-requests: read

jobs:
  prerelease-checks:
    name: Prerelease Checks
    uses: ./.github/workflows/shared-prerelease-checks.yml
    with:
      force: ${{ github.event_name == 'workflow_dispatch' }}

  deploy:
    name: Deploy
    environment: production
    runs-on: ubuntu-latest
    timeout-minutes: 3
    needs: prerelease-checks
    if: ${{ needs.prerelease-checks.outputs.code-changed == 'true' }}

    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: 'true'

      - name: Bump version and push tag
        id: tag
        uses: mathieudutour/github-tag-action@a22cf08638b34d5badda920f9daf6e72c477b07b # v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ""
          default_bump: patch

      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 24
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --filter infra...

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 # v6
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_PROD }}:role/github-actions-cdk-deploy-north-1
          aws-region: eu-north-1

      - name: Perform release
        run: pnpm run cdk:deploy --require-approval broadening
