name: Pull Request Checks

on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]

permissions:
  contents: read
  pull-requests: read

jobs:
  prerelease-checks:
    name: Prerelease Checks
    uses: ./.github/workflows/shared-prerelease-checks.yml
